from __future__ import annotations

import re
import socket
import tempfile
from dataclasses import dataclass
from pathlib import Path

from ..interfaces import ArtifactStore
from .serial import PosixPtyPair

_CONFIG_KEY = re.compile(r"^[A-Za-z0-9_]+$")
_RUNTIME_OWNED_KEYS = {
    "device_id",
    "enable_scheduler",
    "extended_device_id",
    "ftdi_low_latency",
    "listen_address",
    "mqtt_address",
    "panel_type",
    "rssa_device_id",
    "serial_port",
    "sync_panel_time",
    "web_directory",
}


@dataclass(frozen=True)
class PanelFixture:
    panel_type: str
    device_id: str
    rssa_device_id: str | None = None
    extended_device_id: str | None = None
    overrides: tuple[tuple[str, str], ...] = ()


class IsolatedAqualinkdRuntime:
    """Own the PTY, loopback listener reservation, and generated config."""

    def __init__(
        self,
        *,
        temporary_directory: tempfile.TemporaryDirectory[str],
        pty: PosixPtyPair,
        port_socket: socket.socket,
        config_path: Path,
        api_base_url: str,
    ) -> None:
        self._temporary_directory = temporary_directory
        self.pty = pty
        self._port_socket: socket.socket | None = port_socket
        self.config_path = config_path
        self.api_base_url = api_base_url

    @classmethod
    def create(
        cls,
        *,
        web_directory: Path,
        fixture: PanelFixture,
        artifacts: ArtifactStore,
    ) -> IsolatedAqualinkdRuntime:
        resolved_web = web_directory.expanduser().resolve(strict=True)
        cls._validate_fixture(fixture)
        temporary_directory = tempfile.TemporaryDirectory(
            prefix="aqualinkd-validator-panel-free-"
        )
        pty: PosixPtyPair | None = None
        port_socket: socket.socket | None = None
        try:
            pty = PosixPtyPair.create()
            port_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            port_socket.bind(("127.0.0.1", 0))
            port = int(port_socket.getsockname()[1])
            api_base_url = f"http://127.0.0.1:{port}"
            config_path = Path(temporary_directory.name) / "aqualinkd.conf"
            contents = cls._config_contents(
                serial_port=pty.slave_path,
                api_base_url=api_base_url,
                web_directory=resolved_web,
                fixture=fixture,
            )
            config_path.write_text(contents, encoding="utf-8")
            config_path.chmod(0o600)
            artifacts.write_text("effective-aqualinkd.conf", contents)
            return cls(
                temporary_directory=temporary_directory,
                pty=pty,
                port_socket=port_socket,
                config_path=config_path,
                api_base_url=api_base_url,
            )
        except BaseException:
            if port_socket is not None:
                port_socket.close()
            if pty is not None:
                pty.close_now()
            temporary_directory.cleanup()
            raise

    def release_http_port(self) -> None:
        """Release the reservation immediately before starting AqualinkD."""
        port_socket = self._port_socket
        self._port_socket = None
        if port_socket is not None:
            port_socket.close()

    async def close(self) -> None:
        self.release_http_port()
        await self.pty.close()
        self._temporary_directory.cleanup()

    @classmethod
    def _config_contents(
        cls,
        *,
        serial_port: Path,
        api_base_url: str,
        web_directory: Path,
        fixture: PanelFixture,
    ) -> str:
        values = {
            "listen_address": api_base_url,
            "serial_port": str(serial_port),
            "web_directory": f"{web_directory}/",
            "panel_type": fixture.panel_type,
            "device_id": fixture.device_id,
            "enable_scheduler": "no",
            "sync_panel_time": "no",
            "ftdi_low_latency": "no",
            "log_level": "DEBUG",
            "log_msec_ts": "yes",
        }
        if fixture.rssa_device_id is not None:
            values["rssa_device_id"] = fixture.rssa_device_id
        if fixture.extended_device_id is not None:
            values["extended_device_id"] = fixture.extended_device_id
        for key, value in fixture.overrides:
            values[key] = value
        lines = [
            "# Generated by aqualinkd-validator for isolated panel-free testing",
            "# MQTT, sensors, and other external integrations are absent by default.",
        ]
        lines.extend(f"{key} = {value}" for key, value in values.items())
        return "\n".join(lines) + "\n"

    @staticmethod
    def _validate_fixture(fixture: PanelFixture) -> None:
        required_values = {
            "panel_type": fixture.panel_type,
            "device_id": fixture.device_id,
        }
        if fixture.rssa_device_id is not None:
            required_values["rssa_device_id"] = fixture.rssa_device_id
        if fixture.extended_device_id is not None:
            required_values["extended_device_id"] = fixture.extended_device_id
        for key, value in required_values.items():
            if not _CONFIG_KEY.fullmatch(key):
                raise ValueError(f"Invalid AqualinkD configuration key: {key!r}")
            if not value or "\n" in value or "\r" in value:
                raise ValueError(f"Invalid AqualinkD config value for {key}")
        for key, value in fixture.overrides:
            if not _CONFIG_KEY.fullmatch(key):
                raise ValueError(f"Invalid AqualinkD configuration key: {key!r}")
            if key in _RUNTIME_OWNED_KEYS:
                raise ValueError(
                    f"Panel-free fixture cannot override runtime-owned key {key}"
                )
            if not value or "\n" in value or "\r" in value:
                raise ValueError(f"Invalid AqualinkD config value for {key}")
